# Generated by Django 4.2.14 on 2024-07-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('interval', models.CharField(blank=True, choices=[('1d', 'Daily'), ('1wk', 'Weekly'), ('3mo', '3 Monthly'), ('1y', 'Yearly')], default='1d', max_length=16, null=True)),
                ('period', models.CharField(blank=True, choices=[('1d', 'Daily'), ('1wk', 'Weekly'), ('3mo', '3 Monthly'), ('1y', 'Yearly')], default='3mo', max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('exchange_prefix', models.CharField(blank=True, default='', max_length=8, null=True)),
            ],
        ),
    ]
