# Generated by Django 4.2.14 on 2024-07-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_checks', '0002_openposition_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openposition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange_prefix',
            field=models.CharField(blank=True, default='JO', max_length=8, null=True),
        ),
    ]
