# Generated by Django 4.2.14 on 2024-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_checks', '0004_alter_openposition_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='default_interval',
            field=models.CharField(choices=[('1d', 'Daily'), ('1wk', 'Weekly'), ('3mo', '3 Monthly'), ('1y', 'Yearly')], default='1d', max_length=16),
        ),
        migrations.AddField(
            model_name='stock',
            name='default_period',
            field=models.CharField(choices=[('1d', 'Daily'), ('1wk', 'Weekly'), ('3mo', '3 Monthly'), ('1y', 'Yearly')], default='3mo', max_length=16),
        ),
    ]
