# Generated by Django 4.2.14 on 2024-07-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_checks', '0005_stock_default_interval_stock_default_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='platform',
            field=models.CharField(choices=[('stx', 'Satrix'), ('ee', 'Easy Equities')], default='ee', max_length=16),
        ),
    ]
