# Generated by Django 4.2.14 on 2024-07-22 06:56

from django.db import migrations, models

def add_platforms(apps, schema_editor):
    Platform = apps.get_model('daily_checks', 'Platform')
    Platform.objects.bulk_create([
        Platform(code='stx', name='Satrix'),
        Platform(code='ee', name='Easy Equities')
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('daily_checks', '0006_stock_platform'),
    ]

    

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='platform',
        ),
        migrations.RunPython(add_platforms),
    ]
