# Generated by Django 4.2.14 on 2024-07-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_checks', '0007_platform_remove_stock_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='daily_checks.platform'),
            preserve_default=False,
        ),
    ]
