# Generated by Django 4.2.14 on 2024-07-18 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openposition',
            name='stock',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='daily_checks.stock'),
        ),
    ]
