# Generated by Django 4.2.14 on 2024-07-18 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_checks', '0003_alter_openposition_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openposition',
            name='interval',
            field=models.CharField(choices=[('1d', 'Daily'), ('1wk', 'Weekly'), ('3mo', '3 Monthly'), ('1y', 'Yearly')], default='1d', max_length=16),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='period',
            field=models.CharField(choices=[('1d', 'Daily'), ('1wk', 'Weekly'), ('3mo', '3 Monthly'), ('1y', 'Yearly')], default='3mo', max_length=16),
        ),
        migrations.AlterField(
            model_name='openposition',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daily_checks.stock', unique=True),
        ),
    ]
